export type BuiltInTheme = 
  | 'alien'
  | 'argentina'
  | 'audemars_piguet_royal_oak'
  | 'audemars-piguet-royal-oak'
  | 'aurora'
  | 'aurora_tromso'
  | 'aurora-tromso'
  | 'australia'
  | 'autumn'
  | 'autumn_forest'
  | 'autumn-forest'
  | 'bamboo_zen'
  | 'bamboo-zen'
  | 'baseball_diamond'
  | 'baseball-diamond'
  | 'basketball'
  | 'bonsai'
  | 'boxing_ring'
  | 'boxing-ring'
  | 'brazil'
  | 'breitling_navitimer'
  | 'breitling-navitimer'
  | 'cactus'
  | 'canada'
  | 'cartier_santos'
  | 'cartier-santos'
  | 'cherry_blossom'
  | 'cherry-blossom'
  | 'chronograph'
  | 'coral_reef'
  | 'coral-reef'
  | 'cottagecore'
  | 'cricket_stadium'
  | 'cricket-stadium'
  | 'crystal_cave'
  | 'crystal-cave'
  | 'cyberdeck'
  | 'cyberpunk'
  | 'cyberpunk2077'
  | 'cycling_velodrome'
  | 'cycling-velodrome'
  | 'dandelion'
  | 'desert_dunes'
  | 'desert-dunes'
  | 'diver'
  | 'earth_planet'
  | 'earth-planet'
  | 'egypt'
  | 'eiffel_tower'
  | 'eiffel-tower'
  | 'firefly_meadow'
  | 'firefly-meadow'
  | 'football_soccer'
  | 'football-soccer'
  | 'forest'
  | 'formula1_racing'
  | 'formula1-racing'
  | 'france'
  | 'fuji'
  | 'galaxy'
  | 'geode'
  | 'germany'
  | 'glacier_fjord'
  | 'glacier-fjord'
  | 'golf_links'
  | 'golf-links'
  | 'grand_canyon'
  | 'grand-canyon'
  | 'greece'
  | 'gshock'
  | 'hive'
  | 'holo'
  | 'india'
  | 'indonesia'
  | 'israel'
  | 'italy'
  | 'iwc_portugieser'
  | 'iwc-portugieser'
  | 'japan'
  | 'jupiter_planet'
  | 'jupiter-planet'
  | 'kawaii'
  | 'lotus'
  | 'luxury'
  | 'machu_picchu'
  | 'machu-picchu'
  | 'maldives'
  | 'mario'
  | 'mars_planet'
  | 'mars-planet'
  | 'matrix'
  | 'mecha'
  | 'mercury_planet'
  | 'mercury-planet'
  | 'mexico'
  | 'monarch_migration'
  | 'monarch-migration'
  | 'monstera'
  | 'moon_lunar'
  | 'moon-lunar'
  | 'mountain_sunrise'
  | 'mountain-sunrise'
  | 'mushroom'
  | 'neptune_planet'
  | 'neptune-planet'
  | 'netherlands'
  | 'newZealand'
  | 'norway'
  | 'ocean'
  | 'ocean_bioluminescence'
  | 'ocean-bioluminescence'
  | 'omega_speedmaster'
  | 'omega-speedmaster'
  | 'owl'
  | 'patek_philippe_nautilus'
  | 'patek-philippe-nautilus'
  | 'penguin'
  | 'pilot'
  | 'pokemon'
  | 'pyramids'
  | 'quantum'
  | 'racing'
  | 'radar'
  | 'rainforest_canopy'
  | 'rainforest-canopy'
  | 'rolex_daytona'
  | 'rolex-daytona'
  | 'rolex_submariner'
  | 'rolex-submariner'
  | 'russia'
  | 'santorini'
  | 'saturn_planet'
  | 'saturn-planet'
  | 'scuba_diving'
  | 'scuba-diving'
  | 'singapore'
  | 'skateboarding_street'
  | 'skateboarding-street'
  | 'snowboarding_winter'
  | 'snowboarding-winter'
  | 'southAfrica'
  | 'southKorea'
  | 'spain'
  | 'starship'
  | 'sun'
  | 'sun_fusion'
  | 'sun-fusion'
  | 'sunflower'
  | 'surfing_pipeline'
  | 'surfing-pipeline'
  | 'sweden'
  | 'swiss'
  | 'switzerland'
  | 'synthwave'
  | 'tag_heuer_monaco'
  | 'tag-heuer-monaco'
  | 'taj_mahal'
  | 'taj-mahal'
  | 'tennis_slam'
  | 'tennis-slam'
  | 'terrarium'
  | 'thailand'
  | 'thunderstorm_cloud'
  | 'thunderstorm-cloud'
  | 'timemachine'
  | 'titan_edge'
  | 'titan-edge'
  | 'tree_rings'
  | 'tree-rings'
  | 'triathlon'
  | 'uae'
  | 'uk'
  | 'uranus_planet'
  | 'uranus-planet'
  | 'usa'
  | 'venice'
  | 'venus_planet'
  | 'venus-planet'
  | 'vietnam'
  | 'vintage'
  | 'volcano'
  | 'warp'
  | 'waterfall'
;

export interface ClockOptions {
  theme?: BuiltInTheme | string;
  timezone?: string;
  smooth?: boolean;
  size?: string;
  accentColor?: string;
  faceColor?: string;
  handColor?: string;
  showSeconds?: boolean;
  showNumbers?: boolean | "arabic" | "roman";
  showDate?: boolean;
  showTicks?: boolean;
  label?: string;
  blink?: boolean;
}

export interface TimeData {
  hour?: number;
  minute?: number;
  second?: number;
  date?: number;
  day?: number;
  hours: number;
  minutes: number;
  seconds: number;
  milliseconds: number;
  hourAngle: number;
  minuteAngle: number;
  secondAngle: number;
  dateString: string;
  dayString: string;
  monthString: string;
  timeString12: string;
  timeString24: string;
  timezoneName: string;
  isPm: boolean;
}

export interface ThemeColors {
  face: string;
  dialBorder: string;
  hourTicks: string;
  minuteTicks: string;
  numbers: string;
  hourHand: string;
  minuteHand: string;
  secondHand: string;
  accent: string;
  centerCap: string;
  subdialBg?: string;
  glow?: string;
  shadow?: string;
}

export interface ClockThemeRenderer {
  name: string;
  description?: string;
  defaultColors: Partial<ThemeColors>;
  renderDial: (options: ClockOptions, colors: ThemeColors, time: TimeData) => string;
  renderHands: (options: ClockOptions, colors: ThemeColors, time: TimeData) => string;
  renderOverlay?: (options: ClockOptions, colors: ThemeColors, time: TimeData) => string;
  getStyles?: (colors: ThemeColors) => string;
}
